[package]
name = "local_terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
frozen_term = { path = "../../frozen_term", features = ["local-terminal"] }
iced = { git = "https://github.com/iced-rs/iced.git", features = ["debug"] }
